### PR TITLE
Add findParent and findParents helpers

### PR DESCRIPTION
**Pull request by jfelip937**
**DESCRIPTION**

    findParent(el) -> el.parentElement
    findParent(el, query) -> first matched parent
    findParents(el, query) -> array of matches

### CODE REVIEW

**Comment by markets** [comment]
Like it @jfelip937! 

I've some doubts about the name though. Since it returns a single element, maybe `parent()` (singular) would be better 🤔?

**Comment by jfelip937** [comment]
> Like it @jfelip937!
> 
> I've some doubts about the name though. Since it returns a single element, maybe `parent()` (singular) would be better thinking?

@markets Yes I thought about that too. But IMO `parent()` may be confused with an alias of `element.parentElement`. Maybe something like `findInParents` or `findAmongParents` (it's also more coherent with `find` and `findAll`)?

**Comment by markets** [comment]
> But IMO parent() may be confused with an alias of element.parentElement

Right!

Then, I think I'd vote for `parents()`, as it's shorter and more comfortable to use (like all Ralix helpers).

**Review by markets — APPROVED** [review]

**Comment by markets** [comment]
After discussing this more in detail with @jfelip937 and @araluce, we thought that the most useful/comfortable/consistent API is something like:

- parent(element) -> element.parentElement
- parent(el, query) -> first matched parent
- parents(el, query) -> array of matches

**Comment by jfelip937** [comment]
@markets It seems that `parent` is an alias of the object `window` in most browsers. I propose to use `findParent` and `findParents` (coherent with `find` and `findAll` and are short).

**Comment by markets** [comment]
ouch! that's right: https://developer.mozilla.org/en-US/docs/Web/API/Window/parent

let's go with `findParent` and `findParents`, it seems consistent!

**Review by markets — APPROVED** [review]

**Pull request merged**
